### ISSUE TITLE
Viewing multiple positions per well 

### ISSUE THREAD

**Issue by edyoshikun** [czbiohub/iohub#77]
Per our discussion @ziw-liu @ieivanov @talonchandler:

**Our experience and thoughts**
- There is a need to properly display multiple positions within a well in napari. Currently, the `napari-ome-zarr` format does not display multiple positions within a `well`. It only loads `position 0`. 
- Additionally, dragging and dropping a Well with multiple positions creates the behavior in #75, which duplicates the naming of the layers given the number of positions in the well. From this one gets one slider for the position, making it difficult to see or scan through the whole plate.
- One solution is to write `tiled datasets` like in #73 where we stitch multiple positions into a single tiled array. This can be written in `Data.zarr/Row0/Col0/position/0`and will show properly in `napari-ome-zarr`. We need to store in metadata where and what position each chunked (Y,X) array came from to preserve the original position during acquisition.

**The expected behavior we want**
- Easy method to drag and drop a well with multiple positions
- Implement a pyramid structure for viewing the whole plate
- We discussed the potential to add a custom viewer to get us rolling.

Please feel free to add more to this if I missed any points.

**Comment by ieivanov** [comment]
Adding some more notes from our discussion yesterday:

* We would like to be able to display in napari both multiple wells within a well plate, and multiple FOVs within a well.
* Currently displaying multiple wells within a well plate works decently. Here are some limitations
    * Only the first FOV from each well is loaded when using the napari-ome-zarr plugin to display HCS data. I think this behavior is good - it's not immediately practical to display all FOVs from all wells at the same time. A possible extension may be to display a random FOV, rather than the first one.
    * The first FOV within a well needs to be named `0`. This presents a limitation in carrying over the names of the FOVs from the experiment.
    * The array within Position `0` needs to be named `0` - that's largely OK
* Displaying multiple FOVs within a well does not work, and leads to issue described in #75. This is a limitation due to the ome-zarr reader which the napari-ome-zarr plugin uses to load the data.  

One easy solution to both issues would be to write a new (say `napari-iohub`) plugin which will use iohub to read the zarr datasets. A long term fix would be to use pyramids for visualization. Tiling to me seems more of a hack for this application, and we'll run into the problem of trying to display too much data at the same time when loading a whole well plate.

**Comment by ziw-liu** [comment]
Thanks for documenting this issue. While a napari viewer will probably not be part of iohub (which aims to serve other projects as a library), the need to view high-content screening data properly is indeed present. 

`recOrder` currently [contributes a reader to napari](https://github.com/mehta-lab/recOrder/blob/6742be9bf99e2d05d00213d722798dce2e8602f5/recOrder/napari.yaml#L11-L14) by wrapping `WaveorderReader`. As we release iohub, `recOrder` will be updated to depend on it, and I think it is natural to utilizing existing code by @talonchandler in `recOrder view` to address this issue. We can either upgrade the `recOrder` reader or move that functionality into a standalone package.

**Comment by ziw-liu** [comment]
Removing `bug` label since it is not an iohub bug to be writing files according to the NGFF spec.

**Comment by ziw-liu** [comment]
Although we are not clear why it did not work before, but napari-ome-zarr can now view multiple positions in a well (channel as layers) if the FOVs are named as 0, 1, 2, ... Also the napari builtin reader can open arbitrarily named positions as layers.
